### ISSUE TITLE
cannot clone VM with --cspec StaticSpec

### ISSUE THREAD

**Issue by ikozel** [ezrapagel/knife-vsphere#146]
knife vsphere vm clone test3 --template dev_template --cspec StaticSpec --cips 10.102.128.200

ERROR: RbVmomi::Fault: NotFound: The object or item referred to could not be found.

Listing template just fine:
knife vsphere template  list
Template Name: dev_template

If   --cspec   is not specified got diff error:

knife vsphere vm clone test --template dev_template 
Cloning template dev_template to new VM test
ERROR: RbVmomi::Fault: NicSettingMismatch: fault.NicSettingMismatch.summary

Anything missing on how to create VM?

**Comment by swalberg** [comment]
Do you have a customization spec called `StaticSpec` in your vcenter server? What about running `knife vsphere vm clone test3 --template dev_template --cips 10.102.128.200/24`?

**Comment by ikozel** [comment]
did that and ruin into diff error:
ERROR: RbVmomi::Fault: UncustomizableGuest: Customization of the guest operating system 'centos64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations. 



     On Friday, March 27, 2015 1:48 PM, Sean Walberg <notifications@github.com> wrote:
   

 Do you have a customization spec called StaticSpec in your vcenter server? What about running knife vsphere vm clone test3 --template dev_template --cips 10.102.128.200/24?—

**Comment by swalberg** [comment]
It sounds like your template needs the vmware tools updated. Can you convert it to a VM, update the tools, wipe the network config (`rm /etc/udev/rules.d/70-persistent-net.rules /etc/sysconfig/network-scripts/ifcfg-eth0; sync; halt`) and convert it back to a template? Then, try again.

This plugin works by telling the VSphere API what to do with the instance, which VMWare then does by communicating through the VMWare tools. If it's not supported by VMWare and the tools that the template starts with, there's not a lot we can do.

If the VMWare tools update doesn't work, what version of VSphere are you running? I know this works on 5.0, because our CentOS 6.5 templates use LVM.

**Comment by ikozel** [comment]
Working great now. I've done the following to fix my problem:- added customization spec on ESX server.- changed metadata for OS name from centOS to read hat. Thanks for your help!
  


     On Friday, March 27, 2015 3:14 PM, Sean Walberg <notifications@github.com> wrote:
   

 It sounds like your template needs the vmware tools updated. Can you convert it to a VM, update the tools, wipe the network config (rm /etc/udev/rules.d/70-persistent-net.rules /etc/sysconfig/network-scripts/ifcfg-eth0; sync; halt) and convert it back to a template? Then, try again.This plugin works by telling the VSphere API what to do with the instance, which VMWare then does by communicating through the VMWare tools. If it's not supported by VMWare and the tools that the template starts with, there's not a lot we can do.If the VMWare tools update doesn't work, what version of VSphere are you running? I know this works on 5.0, because our CentOS 6.5 templates use LVM.—

**Comment by swalberg** [comment]
Glad to hear that it's working!
