### ISSUE TITLE
knife vsphere vm clone fails

### ISSUE THREAD

**Issue by Learath** [ezrapagel/knife-vsphere#162]
knive vsphere vm clone fails if:
1. dc.hostFolder does not contain any ComputeResources or ClusterComputeResources
2. The first host found does not have access to the requested vlan, datastore or datastorecluster or is in Maintnenance Mode

Suggested fix:
Clean up and implement the following logic in one or more seperate functions:
while (hosts.first.hhost.first.runtime.inMaintenanceMode || !(hosts.first.host.first.network.include?(find_network(get_config(:customization_vlan)))) || !(hosts...include?(find_datastore...) ... datastorecluster)
hosts.shift
end

The reason I'm submitting this issue is to request any pointer/suggestions to help getting this implemented cleanly and accepted upstream.  I currently intend to implement a recursive function, named something like "find_valid_host(dc.hostFolder cust_vlan datastore|datastorecluster)".  I may instead take a hash as input to find_valid_host to allow for future restrictions, or leaving out restrictions easily.

**Comment by swalberg** [comment]
Hi Nick,

Thanks for submitting the bug report and offering to do the work. Until you mentioned it I didn't dig into the host selection, and now I think this will help out with #2, also.

As general guidance we're looking for code that is expressive and improves the clarity of the class. Since we have no tests now I'd prefer to see a minimal implementation rather than a massive refactor. Happy to look at refactors as a second pull request, though.

I'd suggest leaning on the [`Enumerable`](http://ruby-doc.org/core-2.2.2/Enumerable.html) methods over a recursive implementation, as that can be be made to read almost English-like. You could even ditch the `find_`. If the method returns the first valid host or pool then something like

```
rspec = RbVmomi::VIM.VirtualMachineRelocateSpec(pool: first_valid_pool)

def first_valid_pool
  valid_hosts = all_hosts #or something
    .reject { |host| host.runtime.inMaintenanceMode }
    .reject { |host| host.network.blah }
    .reject { |host| some other condition }
  if valid_hosts.empty?
    log_fatal "Doh"
  else
    valid_hosts.first.resourcePool
  end
end
```

I'd also suggest leaving out the restrictions part in the spirit of a minimal implementation, as that can easily be added as another step to the pipeline when we have a clearer idea of the use cases.

Let me know what you think, and I'm always around to help.

**Comment by Learath** [comment]
1. I've been ambushed by Legal, hopefully that will resolve itself this week
2. I've replaced the find_all_in_folder call in generate_clone_spec with a call to what I'm calling "traverse_folders_for_computeresources" based on "traverse_folder_for_vms"
3. I'm including if get_config(:datastore|datastorecluster|customization_vlan) hosts.reject!{|h| !h.datastore|network.include?... followed by "if hosts.empty fatal_exit "no hosts have the requested Datastore|Datastorecluster|Network available!"

I'll send a pull request as soon as I can.
